# Use the official NGINX image as a base image
FROM nginx:alpine

# Copy the static HTML files to the NGINX web directory
COPY ./index.html /usr/share/nginx/html/index.html

# Expose port 80 to access the application
EXPOSE 80
